#! /usr/bin/bash

DIR=./test_res
if [ ! -d "$DIR" ]
then
	mkdir $DIR
fi

fn="$DIR/kpr-00"

echo "Generating network..."
python3 ./src/gen_network.py -o $fn

echo "Getting achievable patterns..."
python3 ./src/get_achievable_patterns.py -i $fn

echo "Calculating crosstalk..."
python3 ./src/calc_crosstalk.py -i $fn -n 1

echo "Done."
