#! /usr/bin/bash

DIR=./sim_results/$(date +%F__%H_%M_%S)
echo $DIR

python3 ./src/fn_gen_models.py $DIR
python3 ./src/fn_simple_scenarios.py $DIR tf_chrom_equiv_pr_bound.out tf_pr_bound.out tfeq-tf -e tf_error_rate.out -o -x #-s 2 5
python3 ./src/fn_simple_scenarios.py $DIR kpr_pr_open.out tf_pr_bound.out kpr-tf -e tf_error_rate.out -o #-s 2 5

echo "Done."
